---
- name: gluu
  hosts: localhost
  connection: local
  become: True
  become_user: root
  gather_facts: False
  tasks:

    - name: install epel repo
      yum:
        state: latest
        name: "{{ required_repositories }}"
      vars:
        required_repositories:
          - epel-release

    - name: gluu repo
      get_url:
        url: https://repo.gluu.org/centos/Gluu-centos7.repo
        dest: /etc/yum.repos.d/gluu.repo
        owner: root
        group: root
        mode: '0444'

    - name: import key
      rpm_key:
        state: present
        key: https://repo.gluu.org/centos/RPM-GPG-KEY-GLUU

    - name: install required packages
      yum:
        state: present
        name: "{{ required_packages }}"
      vars:
        required_packages:
          - gluu-server

    - name: gluu started/enabled
      systemd:
        name: systemd-nspawn@gluu_server.service
        state: started
        enabled: yes

    - name: determine if admin credential exists
      stat:
        path: /etc/gluu_admin
      register: gluu_admin_file

    - name: generate gluu admin credential
      shell: |
        echo -n $(openssl rand -base64 32) > /etc/gluu_admin
        chmod 400 /etc/gluu_admin
      no_log: True
      when: gluu_admin_file.stat.exists == false

    - name: register gluu admin credential
      shell: |
        cat /etc/gluu_admin
      no_log: True
      register: gluu_admin_credential

    - name: gluu-server/certificate-setup scripts
      template:
        src: "{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        owner: root
        group: root
        mode: '0500'
      with_items:
        - gluu-server-setup
        - gluu-certificate-setup

    - name: copy and run scripts in container
      shell: |
        machinectl copy-to gluu_server /usr/local/bin/{{ item }} /usr/local/bin/{{ item }}
        systemd-run --machine=gluu_server /usr/local/bin/{{ item }}
      with_items:
        - gluu-server-setup-shell
        - gluu-server-setup-expect
      ignore_errors: True
      args:
        executable: /bin/bash
        warn: no
