#!/bin/bash

# install packages
yum -y install python2-certbot-apache memcached

# gluu setup
cd /install/community-edition-setup
echo "{{ domain_name }}
{{ friendly_name }}
{{ gluu_admin_credential.stdout }}
Yes
Yes
Yes
Yes
Yes
No
No
Y" | ./setup.py
exit
